### ISSUE TITLE
Upgrade node-sass to ^4.13.0

### ISSUE THREAD

**Issue by DotCoyote** [spryker/sable-for-zed#17]
To be able to use `node@^13.5` please upgrade node-sass to `^4.13.0`

**Comment by tvaleriy** [comment]
Hi @CinKon,

thank you for reporting this request.
It seems to be fixed internally already and new version will be released soon enough.
Have a nice day!

Best,
Spryker Support Team

PS. Please use our support desk next time as such requests can be easily missed - https://support.spryker.com/hc/en-us/requests/new.
